esphome:
  name: d_outside_t
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SONA"
  password: ".mP09190087401"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D Outside T Fallback Hotspot"
    password: "00000000"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "0918"

ota:
  password: "0918"

dallas:
  - pin: GPIO2

# Individual sensors
sensor:
  - platform: dallas
    address: 0x5301192A50520C28
    name: "Outside Temp"
