esphome:
  name: dht_room_1
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "SONA"
  password: ".mP09190087401"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht Room 1 Fallback Hotspot"
    password: "00000000"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "0918"

ota:
  password: "0918"

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "1F Room Temperature"
    humidity:
      name: "1F Room Humidity"
    update_interval: 60s
