esphome:
  name: pzem_em_2
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "SONA"
  password: ".mP09190087401"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pzem Em 2 Fallback Hotspot"
    password: "00000000"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "0918"

ota:
  password: "0918"

# Example configuration entry
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
#  stop_bits: 1

sensor:
  - platform: pzemac
    current:
      name: "RT Current"
    voltage:
      name: "RT Voltage"
    power:
      name: "RT Power"
    frequency:
      name: "Frequency"
    power_factor:
      name: "Power Factor"
    update_interval: 60s
